#  This is manual page in Perl POD format. Read more at
#  http://perldoc.perl.org/perlpod.html or run command:
#
#     perldoc perlpod | less
#
#  To check the syntax:
#
#     podchecker *.pod
#
#  Create manual page with command:
#
#    pod2man PAGE.N.pod > PAGE.N

=pod

=head1 NAME

wmshutdown - suid program called by wmshutdown(1) to call /sbin/shutdown

=head1 SYNOPSIS

  wmshutdown-run

=head1 DESCRIPTION

Wmshutdown-run is helper program for wmshutdown(1) that allows user to
shutdown or reboot the workstation just by clickig a button on your
desktop.

=head1 OPTIONS

None.

=head1 ENVIRONMENT

None.

=head1 FILES

None.

=head1 SEE ALSO

wmshutdown-run(1)

=head1 AUTHORS

This manual page was written by Jari Aalto <jari.aalto@cante.net>, for
the Debian GNU system (but may be used by others). Released under
license GNU GPL v2 or (at your option) any later version. For more
information about license, visit <http://www.gnu.org/copyleft/gpl.html>.

=cut
